osx_image: xcode10.2
language: objective-c
xcode_sdk: iphonesimulator12.1

xcode_project: RAMAnimatedTabBarDemo/RAMAnimatedTabBarDemo.xcodeproj
xcode_scheme: RAMAnimatedTabBarController

# whitelist
branches:
only:
- master
